### ISSUE TITLE
Match PC JD/Reaction Time values

### ISSUE THREAD

**Issue by Solaris9** [Metalit/QuestJDFixer#2]
As the title says, pc/quest values don't really match up. On PC I would use a 0.45s reaction time and before reaction time update around 16-18 JD but on quest I have to set it around 6 minimum and 9 maximum and change the other slider around 0.5. I don't really know what values these are as it's not 9 JD and I'm not sure what the 0.5 is doing other than making the JD closer or further. If there's some way to make the quest version match the PC version with at least the JD so 16 JD works on both

**Comment by Metalit** [comment]
There definitely is an issue with the terminology and how it's used in various places. Both jump duration and jump distance, due to how they appear in the game's code, are sometimes used to refer to either the *half* or *full* jump distance / duration. And for some reason, the *half* jump distance is equal to the *entire* distance from where the note becomes visible to where you would cut it, and the *full* jump distance is double that. Jump duration is the same in terms of half vs full.
(For what the difference is between jump distance and duration, the duration being the 0.5 you mentioned, a more focused explanation is present on the README of this repository.)
If I were the first one to mess with it, I would have always used the half values, but both of them have been scattered all around without label at this point, including right next to each other. As such, it was a real mess for me to decide which to use for which value, due to the presence of the PC mod and other popular tools, and discussions with other modders. In the end I decided to use the previous units I had used in the original 1.17.1 version of this mod before I examined the units' meanings more closely, as I figured there would likely be more people who had used that version than there would be people that switched from PC to quest native. I'm also not familiar with how the PC mod works, having never played the game on steam, so I likely wouldn't be able to imitate it exactly. (Maybe I shouldn't have copied its name...)
So to answer your question, it looks like the PC mod uses the *full* jump distance, 16-18, which would translate to 8-9 for the *half* jump distance used in the quest mod. If you want to specify that exactly, there's a switch above the JD slider that toggles whether you want to lock the jump distance or duration. (The sliders below that are the bounds, mostly intended to be used in conjunction with duration.) And you're correct that the 0.5, when you have it in jump duration mode, does nothing other than make the JD closer or further.
